standard_git_server: "github.com"
servers:
    github.com:
        zip: "https://github.com/$git_user/$git_repository/archive/$git_branch.zip"
        path: "$git_repository-$git_branch/"

    gitlab.com:
        zip: "https://gitlab.com/$git_user/$git_repository/-/archive/$git_branch/$git_repository-$git_branch.zip"
        path: "$git_repository-$git_branch/"

    bitbucket.org:
        zip: "https://bitbucket.org/$git_user/$git_repository/get/$git_branch.zip"
        path: "$git_user-$git_repository-*"
