name: "Tridymite"
decription: "Tridymite package manager."
information: |
"Install packages from GitHub, GitLab or other Git-Servers using Tridymite!
Try it:

    sudo tridy -i user:repo@server
    sudo tridy -i triploit:tridymite@github.com

You can leave off the @server. GitHub is the standard Git server. So
also this will work:

    sudo tridy -i user:repo
    sudo tridy -i triploit:tridymite"

products:
    - ./tridymite_dir/*: /usr/share/tridymite/

links:
    - /usr/share/tridymite/tridy: /usr/bin/tridy
