name: "Tridymite"
decription: "Just a really short description."
information: |
    "Here comes really long textes, that describe what you can do with this package,
    maybe some help. Like a little man page. Or just create a man page for this
    program, install it (as a product) and let the user know how to see the man page.

    For example:
        
    Install packages from GitHub, GitLab or other Git-Servers by using Tridymite!
    Try it:
        
        sudo tridy install user:repo@server
        sudo tridy install triploit:tridymite@github.com
        
    You can leave off the @server. GitHub is the standard Git server. So
    also this will work:
        
        sudo tridy install user:repo
        sudo tridy install triploit:tridymite"


dependencies:
    - arg: "user:repo@github"
    - git: "https://github.com/user/repo.git"

products:
    - ./tridy: /usr/bin/tridy