name: "Tridymite"
decription: "Just a really short description."
information: |
    "Install packages from GitHub, GitLab or other Git-Servers by using Tridymite!
    Try it:
        
        sudo tridy install user:repo@server
        sudo tridy install triploit:tridymite@github.com
        
    You can leave off the @server. GitHub is the standard Git server. So
    also this will work:
        
        sudo tridy install user:repo
        sudo tridy install triploit:tridymite"

dependencies:
    - git:
        url: "https://github.com/jbeder/yaml-cpp"
        type: "cmake"

products:
    - ./tridy: /usr/bin/tridy
    - ./pkg/conf: /usr/opt/